# C
COLOR_BLACK = (0, 0, 0)
COLOR_GREEN = (0, 255, 120)
COLOR_LEVEL = (237, 52, 27)
COLOR_OPTION = (0, 255, 255)
COLOR_RED = (255, 60, 60)
COLOR_SELECTED = (255, 255, 0)
COLOR_TITLE = (242, 155, 53)
COLOR_WHITE = (255, 255, 255)

# D
DEFAULT_PLAYER_NAME = "PLAYER"

# F
FONT_INFO_SIZE = 30
FONT_MENU_SIZE = 60
FONT_NAME = "Lucida Sans Typewriter"
FONT_SCORE_SIZE = 70
FONT_TITLE_SIZE = 90

# G
GRAVITY = 0.7
GROUND_Y = 520

# J
JUMP_FORCE = -15

# L
LEVEL_GOALS = {
    1: 1000,
    2: 2000,
    3: 3500,
    4: 5000
}

LEVEL_GROUND_Y = {
    1: 520,
    2: 520,
    3: 530,
    4: 510
}

LEVEL_SPEED = {
    1: 6,
    2: 8,
    3: 10,
    4: 12
}

# M
MAX_PLAYER_NAME_LENGTH = 10
MENU_LEFT_X = 80
MENU_OPTIONS = ("START", "SCORE", "SETTINGS", "EXIT")
MENU_SPACING_Y = 80
MENU_START_Y = 170
MUSIC_SLIDER_Y = 265

# O
OBSTACLE_SPAWN_TIME = 80

# P
PATH_CHARACTER_JUMP = "assets/Images/character/jump"
PATH_CHARACTER_RUN = "assets/Images/character/run"
PATH_MENU_BG = "assets/Images/menu/menuBg.png"
PATH_MUSIC_BG = "assets/sounds/musicBg.mp3"
PATH_MUSIC_LEVELS = "assets/sounds/musicLevels.mp3"
PATH_MUSIC_SCORE = "assets/sounds/musicScore.mp3"
PATH_SCORE_BG = "assets/Images/score/scoreBg.png"

PAUSE_OPTIONS = ("RESUME", "MAIN MENU")

PLAYER_ANIMATION_SPEED = 0.25
PLAYER_HEIGHT = 80
PLAYER_WIDTH = 100
PLAYER_X = 120

# S
SETTINGS_OPTIONS = ("MUSIC VOLUME", "SFX VOLUME")

SFX_SLIDER_Y = 355

SLIDER_HEIGHT = 18
SLIDER_WIDTH = 420

STATE_MENU = "menu"
STATE_NAME_INPUT = "name_input"
STATE_PAUSED = "paused"
STATE_PLAYING = "playing"
STATE_SCORE = "score"
STATE_SETTINGS = "settings"

# T
TEXT_GAME_HELP = "SPACE = PULAR | ESC = PAUSE"
TEXT_MENU_HELP = "SETAS/MOUSE - NAVEGAR | ENTER/CLICK - SELECIONAR"
TEXT_NAME_INPUT_HELP = "ENTER - COMEÇAR | ESC - VOLTAR | BACKSPACE - APAGAR"
TEXT_NAME_INPUT_TITLE = "DIGITE SEU NOME"
TEXT_SCORE_BACK = "ESC OU CLICK PARA VOLTAR"
TEXT_SETTINGS_BACK = "ESC / ENTER PARA VOLTAR"
TEXT_SETTINGS_HELP = "UP/DOWN-SELECIONAR | LEFT/RIGHT-AJUSTAR | MOUSE-ARRASTAR"

# U
END_OPTIONS = ("RESTART", "MAIN MENU")

# W
WINDOW_FPS = 60
WINDOW_HEIGHT = 570
WINDOW_WIDTH = 1020